# frozen_string_literal: true

RSpec.describe Kettle::Jem::Appraisals::ActiveRecordSupportGemfileGenerator do
  let(:tmpdir) { File.join(Dir.pwd, "tmp", "test_activerecord_support_gemfiles") }
  let(:generator) { described_class.new(base_dir: tmpdir) }
  let(:support_dir) { File.join(tmpdir, "gemfiles", "modular", "activerecord_support") }

  before { FileUtils.mkdir_p(tmpdir) }
  after { FileUtils.rm_rf(tmpdir) }

  def sqlite3_line(activerecord_version)
    requirements = Kettle::Rb::GemDependencies.requirements("activerecord", activerecord_version, "sqlite3")
    %(gem "sqlite3", #{requirements.map(&:inspect).join(", ")}, platforms: [:ruby])
  end

  describe "#generate" do
    it "writes one support gemfile per kettle-rb sqlite3 requirement the matrix uses" do
      results = generator.generate(%w[6.1 7.0 7.1 8.0 8.1])

      expect(results).to eq(
        "gemfiles/modular/activerecord_support/v6.0.gemfile" => :written,
        "gemfiles/modular/activerecord_support/v7.1.gemfile" => :written,
        "gemfiles/modular/activerecord_support/v8.0.gemfile" => :written
      )

      legacy = File.read(File.join(support_dir, "v6.0.gemfile"))
      expect(legacy).to include("# Generated by kettle-jem-appraisals\n")
      expect(legacy).to include("# Database drivers for ActiveRecord 6.0–7.0:")
      expect(legacy).to include("# sqlite3 requirement from kettle-rb: rails v7.0")
      expect(legacy).to include(sqlite3_line("6.1"))
      expect(legacy).to include(%(platforms :jruby do\n  gem "activerecord-jdbcsqlite3-adapter", ">= 1.3"\n  gem "bigdecimal", ">= 1"\nend\n))

      expect(File.read(File.join(support_dir, "v7.1.gemfile"))).to include("ActiveRecord 7.1–7.2", sqlite3_line("7.1"))
      expect(File.read(File.join(support_dir, "v8.0.gemfile"))).to include("ActiveRecord 8.0+", sqlite3_line("8.0"))
    end

    it "produces valid Ruby" do
      generator.generate(%w[4.2 5.2 7.1 8.0])

      Dir.glob(File.join(support_dir, "*.gemfile")).each do |path|
        expect { RubyVM::InstructionSequence.compile(File.read(path)) }.not_to raise_error
      end
    end

    it "notes sqlite3 advisories that no allowed release fixes" do
      unfixed = generator.unfixed_sqlite3_advisories("7.0")
      expect(unfixed).not_to be_empty

      generator.generate(["7.0"])

      expect(File.read(File.join(support_dir, "v6.0.gemfile")))
        .to include("# kettle-rb: no sqlite3 release allowed here fixes #{unfixed.join(", ")}\n")
      expect(generator.unfixed_sqlite3_advisories("8.0")).to be_empty
    end

    it "writes an unconstrained support gemfile for ActiveRecord older than the recorded data" do
      expect(generator.generate(["4.2"])).to eq("gemfiles/modular/activerecord_support/unknown.gemfile" => :written)

      content = File.read(File.join(support_dir, "unknown.gemfile"))
      expect(content).to include("ActiveRecord without recorded sqlite3 requirements", %(gem "sqlite3", platforms: [:ruby]))
      expect(generator.sqlite3_requirements("4.2")).to be_empty
    end

    it "keeps hand-maintained support gemfiles untouched" do
      path = File.join(support_dir, "v8.0.gemfile")
      FileUtils.mkdir_p(support_dir)
      File.write(path, "gem \"sqlite3\", \"~> 2.9\"\n")

      expect(generator.generate(["8.0"])).to eq("gemfiles/modular/activerecord_support/v8.0.gemfile" => :kept)
      expect(File.read(path)).to eq("gem \"sqlite3\", \"~> 2.9\"\n")
    end

    it "regenerates support gemfiles it previously generated" do
      path = File.join(support_dir, "v8.0.gemfile")
      FileUtils.mkdir_p(support_dir)
      File.write(path, "# frozen_string_literal: true\n\n# Generated by kettle-jem-appraisals\ngem \"stale\"\n")

      expect(generator.generate(["8.1"])).to eq("gemfiles/modular/activerecord_support/v8.0.gemfile" => :written)
      expect(File.read(path)).not_to include("stale")
    end

    it "removes support gemfiles generated by 0.1.4 and earlier but keeps hand-maintained ones" do
      generated = File.join(tmpdir, "gemfiles", "modular", "activerecord_support_modern.gemfile")
      hand_maintained = File.join(tmpdir, "gemfiles", "modular", "activerecord_support.gemfile")
      FileUtils.mkdir_p(File.dirname(generated))
      File.write(generated, "# Generated by kettle-jem-appraisals\ngem \"sqlite3\", \">= 2.1\"\n")
      File.write(hand_maintained, "gem \"sqlite3\", \"~> 1.7\"\n")

      results = generator.generate(["8.0"])

      expect(results).to include("gemfiles/modular/activerecord_support_modern.gemfile" => :removed)
      expect(results).not_to have_key("gemfiles/modular/activerecord_support.gemfile")
      expect(File).not_to exist(generated)
      expect(File.read(hand_maintained)).to eq("gem \"sqlite3\", \"~> 1.7\"\n")
    end
  end

  describe "#eval_path_for" do
    it "maps each ActiveRecord version to the support gemfile for its sqlite3 requirement" do
      expect(generator.eval_path_for("5.2")).to eq("modular/activerecord_support/v5.2.gemfile")
      expect(generator.eval_path_for("7.0.8")).to eq("modular/activerecord_support/v6.0.gemfile")
      expect(generator.eval_path_for("7.2")).to eq("modular/activerecord_support/v7.1.gemfile")
      expect(generator.eval_path_for("9.0")).to eq("modular/activerecord_support/v8.0.gemfile")
      expect(generator.eval_path_for("not a version")).to eq("modular/activerecord_support/unknown.gemfile")
    end
  end

  describe ".support_gemfile?" do
    it "recognizes current and legacy support gemfiles with or without the gemfiles/ prefix" do
      expect(described_class.support_gemfile?("modular/activerecord_support/v7.1.gemfile")).to be(true)
      expect(described_class.support_gemfile?("gemfiles/modular/activerecord_support_modern.gemfile")).to be(true)
      expect(described_class.support_gemfile?("modular/activerecord_support.gemfile")).to be(true)
      expect(described_class.support_gemfile?("modular/combustion.gemfile")).to be(false)
    end
  end
end
