# frozen_string_literal: true

RSpec.describe Kettle::Jem::Appraisals::ActiveRecordSupportGemfileGenerator do
  let(:tmpdir) { File.join(Dir.pwd, "tmp", "test_activerecord_support_gemfiles") }
  let(:generator) { described_class.new(base_dir: tmpdir) }
  let(:legacy_path) { File.join(tmpdir, "gemfiles", "modular", "activerecord_support.gemfile") }
  let(:modern_path) { File.join(tmpdir, "gemfiles", "modular", "activerecord_support_modern.gemfile") }

  before { FileUtils.mkdir_p(tmpdir) }
  after { FileUtils.rm_rf(tmpdir) }

  describe "#generate" do
    it "writes both support gemfiles with engine-specific drivers" do
      results = generator.generate

      expect(results).to eq(
        "gemfiles/modular/activerecord_support.gemfile" => :written,
        "gemfiles/modular/activerecord_support_modern.gemfile" => :written
      )

      legacy = File.read(legacy_path)
      expect(legacy).to include("# Generated by kettle-jem-appraisals\n")
      expect(legacy).to include('gem "sqlite3", ">= 1.4", "< 1.5", platforms: [:ruby]')
      expect(legacy).to include(%(platforms :jruby do\n  gem "activerecord-jdbcsqlite3-adapter", ">= 1.3"\n  gem "bigdecimal", ">= 1"\nend\n))

      modern = File.read(modern_path)
      expect(modern).to include('gem "sqlite3", ">= 2.1", platforms: [:ruby]')
      expect(modern).to include('gem "activerecord-jdbcsqlite3-adapter", ">= 1.3"')
    end

    it "produces valid Ruby" do
      generator.generate

      [legacy_path, modern_path].each do |path|
        expect { RubyVM::InstructionSequence.compile(File.read(path)) }.not_to raise_error
      end
    end

    it "keeps hand-maintained support gemfiles untouched" do
      FileUtils.mkdir_p(File.dirname(legacy_path))
      File.write(legacy_path, "gem \"sqlite3\", \"~> 1.7\"\n")

      results = generator.generate

      expect(results.fetch("gemfiles/modular/activerecord_support.gemfile")).to eq(:kept)
      expect(File.read(legacy_path)).to eq("gem \"sqlite3\", \"~> 1.7\"\n")
      expect(File.read(modern_path)).to include("# Generated by kettle-jem-appraisals")
    end

    it "regenerates support gemfiles it previously generated" do
      FileUtils.mkdir_p(File.dirname(modern_path))
      File.write(modern_path, "# frozen_string_literal: true\n\n# Generated by kettle-jem-appraisals\ngem \"stale\"\n")

      expect(generator.generate.fetch("gemfiles/modular/activerecord_support_modern.gemfile")).to eq(:written)
      expect(File.read(modern_path)).not_to include("stale")
    end
  end

  describe "#eval_path_for" do
    it "uses the legacy support gemfile below ActiveRecord 7.2" do
      expect(generator.eval_path_for("5.2")).to eq("modular/activerecord_support.gemfile")
      expect(generator.eval_path_for("7.1.6")).to eq("modular/activerecord_support.gemfile")
    end

    it "uses the modern support gemfile from ActiveRecord 7.2" do
      expect(generator.eval_path_for("7.2")).to eq("modular/activerecord_support_modern.gemfile")
      expect(generator.eval_path_for("8.0.1")).to eq("modular/activerecord_support_modern.gemfile")
    end
  end

  describe ".support_gemfile?" do
    it "recognizes support gemfiles with or without the gemfiles/ prefix" do
      expect(described_class.support_gemfile?("modular/activerecord_support.gemfile")).to be(true)
      expect(described_class.support_gemfile?("gemfiles/modular/activerecord_support_modern.gemfile")).to be(true)
      expect(described_class.support_gemfile?("modular/combustion.gemfile")).to be(false)
    end
  end
end
