# frozen_string_literal: true

RSpec.describe Kettle::Jem::Appraisals::CLI do
  let(:project_dir) { File.join(Dir.pwd, "tmp", "test_cli_activerecord_support") }
  let(:cli) { described_class.new([], project_dir: project_dir) }
  let(:tier1_gems) { [{"name" => "activerecord"}] }
  let(:entries) do
    [
      {name: "kja-ar-6-1-r2.6", tier1_name: "activerecord", tier1_version: "6.1"},
      {name: "kja-ar-8-0-r3", tier1_name: "activerecord", tier1_version: "8.0", extra_gemfiles: ["modular/combustion.gemfile"]}
    ]
  end

  before { FileUtils.mkdir_p(project_dir) }
  after { FileUtils.rm_rf(project_dir) }

  describe "#annotate_activerecord_support" do
    it "generates support gemfiles and wires the one matching each entry's ActiveRecord version" do
      expect {
        cli.send(:annotate_activerecord_support, entries, tier1_gems, {})
      }.to output(include("Wrote gemfiles/modular/activerecord_support/v6.0.gemfile")).to_stdout
        .and output(include("no sqlite3 release allowed for activerecord 6.1")).to_stderr

      expect(entries.first[:extra_gemfiles]).to eq(["modular/activerecord_support/v6.0.gemfile"])
      expect(entries.last[:extra_gemfiles]).to eq(["modular/activerecord_support/v8.0.gemfile", "modular/combustion.gemfile"])
      expect(File).to exist(File.join(project_dir, "gemfiles/modular/activerecord_support/v8.0.gemfile"))
    end

    it "reports removed legacy support gemfiles" do
      legacy = File.join(project_dir, "gemfiles/modular/activerecord_support_modern.gemfile")
      FileUtils.mkdir_p(File.dirname(legacy))
      File.write(legacy, "# Generated by kettle-jem-appraisals\n")

      expect {
        cli.send(:annotate_activerecord_support, entries.last(1), tier1_gems, {})
      }.to output(include("Removed stale generated gemfiles/modular/activerecord_support_modern.gemfile")).to_stdout
    end

    it "does nothing when activerecord is not a tier1 gem" do
      cli.send(:annotate_activerecord_support, entries, [{"name" => "sequel"}], {})

      expect(entries.first).not_to have_key(:extra_gemfiles)
      expect(Dir.exist?(File.join(project_dir, "gemfiles"))).to be(false)
    end

    it "can be disabled with activerecord_support: false" do
      cli.send(:annotate_activerecord_support, entries, tier1_gems, {"activerecord_support" => false})

      expect(entries.first).not_to have_key(:extra_gemfiles)
      expect(Dir.exist?(File.join(project_dir, "gemfiles"))).to be(false)
    end

    it "defers to support gemfiles already configured in appraisal_gemfiles" do
      matrix = {"appraisal_gemfiles" => ["gemfiles/modular/activerecord_support.gemfile"]}

      cli.send(:annotate_activerecord_support, entries, tier1_gems, matrix)

      expect(entries.first).not_to have_key(:extra_gemfiles)
      expect(Dir.exist?(File.join(project_dir, "gemfiles"))).to be(false)
    end
  end

  describe "#warn_security_advisories" do
    it "warns about unfixed advisories and exact patch versions below the security floor" do
      matrix_entries = [
        {tier1_name: "activerecord", tier1_version: "7.0"},
        {tier1_name: "activerecord", tier1_version: "7.0"},
        {tier1_name: "activerecord", tier1_version: "7.1.0", tier2_name: "sequel", tier2_version: "5.0"}
      ]
      floor = Kettle::Rb::GemFloors.floor("activerecord", "7.1")

      expect { cli.send(:warn_security_advisories, matrix_entries) }
        .to output(
          include("kettle-rb: no activerecord 7.0 release fixes", "CVE-2025-55193", "activerecord 7.1.0 is pinned below the security floor #{floor}")
        ).to_stderr
    end

    it "stays quiet for untracked gems and series without unfixed advisories" do
      matrix_entries = [{tier1_name: "sequel", tier1_version: "5.0"}, {tier1_name: "activerecord", tier1_version: "8.1"}]

      expect { cli.send(:warn_security_advisories, matrix_entries) }.not_to output.to_stderr
    end
  end

  describe "#annotate_extra_gemfiles" do
    it "merges configured gemfiles with gemfiles already on the entry" do
      entry = {name: "kja-ar-8-0-r3", extra_gemfiles: ["modular/activerecord_support/v8.0.gemfile"]}

      cli.send(:annotate_extra_gemfiles, [entry], ["modular/combustion.gemfile", "modular/activerecord_support/v8.0.gemfile"])

      expect(entry[:extra_gemfiles]).to eq(["modular/activerecord_support/v8.0.gemfile", "modular/combustion.gemfile"])
    end
  end

  describe "config file location" do
    it "reads appraisal_matrix from .structuredmerge/kettle-jem.yml" do
      FileUtils.mkdir_p(File.join(project_dir, ".structuredmerge"))
      File.write(File.join(project_dir, ".structuredmerge/kettle-jem.yml"), "appraisal_matrix:\n  mode: minor\n")

      expect(cli.send(:load_config)).to eq("appraisal_matrix" => {"mode" => "minor"})
    end
  end
end
