# frozen_string_literal: true

RSpec.describe Kettle::Jem::Appraisals::ModularGemfileGenerator do
  let(:tmpdir) { File.join(Dir.pwd, "tmp", "test_modular_gemfiles") }
  let(:generator) { described_class.new(base_dir: tmpdir) }

  before { FileUtils.mkdir_p(tmpdir) }
  after { FileUtils.rm_rf(tmpdir) }

  def content_of(path)
    File.read(File.join(tmpdir, path))
  end

  describe "#generate" do
    it "creates a modular gemfile for a tier1 gem with its security floor" do
      path = generator.generate(
        gem_name: "activerecord",
        version: "7.1",
        ruby_series: "r3",
        sub_deps: {"sqlite3" => "1.6.9"}
      )

      expect(path).to eq("gemfiles/modular/activerecord/r3/v7.1.gemfile")
      expect(File.exist?(File.join(tmpdir, path))).to be true

      floor = Kettle::Rb::GemFloors.floor("activerecord", "7.1")
      content = content_of(path)
      expect(content).to include(%(gem "activerecord", "~> 7.1.0", ">= #{floor}"\n))
      expect(content).to include('gem "sqlite3", "~> 1.6.9"')
    end

    it "adds the security floor to tracked sub-dependencies resolved below it" do
      floor = Kettle::Rb::GemFloors.floor("activesupport", "7.1")
      path = generator.generate(gem_name: "activerecord", version: "7.1", ruby_series: "r3", sub_deps: {"activesupport" => "7.1.0"})

      expect(content_of(path)).to include(%(gem "activesupport", "~> 7.1.0", ">= #{floor}"\n))
    end

    it "notes advisories that no release in the series fixes" do
      unpatched = Kettle::Rb::GemFloors.unpatched_advisories("activerecord", "7.0")
      expect(unpatched).not_to be_empty

      path = generator.generate(gem_name: "activerecord", version: "7.0", ruby_series: "r2")

      expect(content_of(path)).to include("# kettle-rb: no activerecord 7.0 release fixes #{unpatched.join(", ")}\ngem \"activerecord\"")
    end

    it "leaves untracked gems without floors or notes" do
      path = generator.generate(gem_name: "sequel", version: "5.0", ruby_series: "r3")

      expect(Dir.exist?(File.join(tmpdir, "gemfiles", "modular", "sequel", "r3"))).to be true
      expect(content_of(path)).to eq(%(# frozen_string_literal: true\n\n# Generated by kettle-jem-appraisals\ngem "sequel", "~> 5.0.0"\n\n))
    end
  end

  describe "#generate_tier2" do
    it "creates a tier2 gemfile" do
      path = generator.generate_tier2(gem_name: "omniauth", version: "2.1", ruby_series: "r3")

      expect(path).to eq("gemfiles/modular/omniauth/r3/v2.1.gemfile")
      expect(content_of(path)).to include('gem "omniauth", "~> 2.1.0"')
    end

    it "keeps exact patch requirements intact" do
      path = generator.generate_tier2(gem_name: "omniauth", version: "2.1.3", ruby_series: "r3")

      expect(content_of(path)).to include('gem "omniauth", "~> 2.1.3"')
    end

    it "keeps an exact patch version below the security floor pinned and notes it" do
      floor = Kettle::Rb::GemFloors.floor("activerecord", "7.1")
      path = generator.generate_tier2(gem_name: "activerecord", version: "7.1.0", ruby_series: "r3")

      content = content_of(path)
      expect(content).to include(%(gem "activerecord", "~> 7.1.0"\n))
      expect(content).to include("# kettle-rb: activerecord 7.1.0 is below the activerecord security floor #{floor}")
    end
  end
end
