# frozen_string_literal: true

require "fileutils"

module Kettle
  module Jem
    module Appraisals
      # Generates the modular gemfiles that give ActiveRecord test suites a
      # database driver on every engine: +sqlite3+ on MRI/TruffleRuby and
      # +activerecord-jdbcsqlite3-adapter+ (plus +bigdecimal+) on JRuby.
      #
      # Two variants exist because +sqlite3+ 2.x is only supported by
      # ActiveRecord >= 7.2, while older ActiveRecord needs the 1.4 series.
      # The JDBC adapter's release series tracks ActiveRecord (52.x, 61.x, 72.x…),
      # so an open requirement lets Bundler pick the adapter matching the
      # resolved ActiveRecord.
      #
      # Files that exist without the {GENERATED_HEADER} are treated as
      # hand-maintained and are never overwritten.
      #
      # @example
      #   generator = ActiveRecordSupportGemfileGenerator.new(base_dir: "/path/to/gem")
      #   generator.generate
      #   generator.eval_path_for("7.1.6") #=> "modular/activerecord_support.gemfile"
      class ActiveRecordSupportGemfileGenerator
        # @return [String] header marking a support gemfile as generated (and safe to regenerate)
        GENERATED_HEADER = "# Generated by kettle-jem-appraisals"

        # @return [String] support gemfile for ActiveRecord below {MODERN_ACTIVERECORD}
        LEGACY_PATH = "gemfiles/modular/activerecord_support.gemfile"

        # @return [String] support gemfile for ActiveRecord at or above {MODERN_ACTIVERECORD}
        MODERN_PATH = "gemfiles/modular/activerecord_support_modern.gemfile"

        # @return [Gem::Version] first ActiveRecord release that supports sqlite3 2.x
        MODERN_ACTIVERECORD = Gem::Version.new("7.2")

        # @return [Hash{String => Hash}] per-variant sqlite3 requirements and description
        VARIANTS = {
          LEGACY_PATH => {sqlite3: [">= 1.4", "< 1.5"], label: "ActiveRecord < 7.2"},
          MODERN_PATH => {sqlite3: [">= 2.1"], label: "ActiveRecord >= 7.2"}
        }.freeze

        class << self
          # @param path [String] a gemfile path, with or without the leading +gemfiles/+
          # @return [Boolean] whether +path+ names one of the ActiveRecord support gemfiles
          def support_gemfile?(path)
            normalized = path.to_s.strip.sub(%r{\Agemfiles/}, "")
            VARIANTS.keys.any? { |variant| variant.delete_prefix("gemfiles/") == normalized }
          end
        end

        # @return [String] absolute path to the project root
        attr_reader :base_dir

        # @param base_dir [String] path to the project root
        def initialize(base_dir: Dir.pwd)
          @base_dir = base_dir
        end

        # Writes both support gemfiles, skipping any hand-maintained file.
        #
        # @return [Hash{String => Symbol}] relative path => +:written+ or +:kept+
        def generate
          VARIANTS.each_with_object({}) do |(relative_path, variant), results|
            absolute = File.join(base_dir, relative_path)
            if File.exist?(absolute) && !File.read(absolute).include?(GENERATED_HEADER)
              results[relative_path] = :kept
              next
            end

            FileUtils.mkdir_p(File.dirname(absolute))
            File.write(absolute, build_content(variant))
            results[relative_path] = :written
          end
        end

        # @param activerecord_version [String, Gem::Version] the entry's ActiveRecord version
        # @return [String] the matching support gemfile, relative to +gemfiles/+ (for +eval_gemfile+)
        def eval_path_for(activerecord_version)
          path = (Gem::Version.new(activerecord_version.to_s) >= MODERN_ACTIVERECORD) ? MODERN_PATH : LEGACY_PATH
          path.delete_prefix("gemfiles/")
        end

        private

        def build_content(variant)
          sqlite3 = [%("sqlite3"), *variant.fetch(:sqlite3).map(&:inspect), "platforms: [:ruby]"].join(", ")
          <<~GEMFILE
            # frozen_string_literal: true

            #{GENERATED_HEADER}
            # Database drivers for #{variant.fetch(:label)}: sqlite3 on MRI/TruffleRuby,
            # activerecord-jdbcsqlite3-adapter on JRuby (its release series tracks ActiveRecord).
            gem #{sqlite3}

            platforms :jruby do
              gem "activerecord-jdbcsqlite3-adapter", ">= 1.3"
              gem "bigdecimal", ">= 1"
            end
          GEMFILE
        end
      end
    end
  end
end
