# frozen_string_literal: true

require "fileutils"
require "kettle/rb"

module Kettle
  module Jem
    module Appraisals
      # Generates the modular gemfiles that give ActiveRecord test suites a
      # database driver on every engine: +sqlite3+ on MRI/TruffleRuby and
      # +activerecord-jdbcsqlite3-adapter+ (plus +bigdecimal+) on JRuby.
      #
      # The sqlite3 requirement comes from +Kettle::Rb::GemDependencies+, which
      # records what each ActiveRecord series' sqlite3 adapter declares. One
      # support gemfile is written per run of consecutive ActiveRecord series
      # sharing a requirement, named after the oldest series in the run
      # (+gemfiles/modular/activerecord_support/v6.0.gemfile+ covers 6.0–7.0).
      # ActiveRecord newer than the recorded series uses the newest run.
      #
      # The JDBC adapter's release series tracks ActiveRecord (52.x, 61.x, 72.x…),
      # so an open requirement lets Bundler pick the adapter matching the
      # resolved ActiveRecord.
      #
      # Files that exist without the {GENERATED_HEADER} are treated as
      # hand-maintained and are never overwritten.
      #
      # @example
      #   generator = ActiveRecordSupportGemfileGenerator.new(base_dir: "/path/to/gem")
      #   generator.generate(["7.1", "8.0"])
      #   generator.eval_path_for("7.1.6") #=> "modular/activerecord_support/v7.1.gemfile"
      class ActiveRecordSupportGemfileGenerator
        # @return [String] header marking a support gemfile as generated (and safe to regenerate)
        GENERATED_HEADER = "# Generated by kettle-jem-appraisals"

        # @return [String] directory holding the support gemfiles
        SUPPORT_DIR = "gemfiles/modular/activerecord_support"

        # @return [String] support gemfile for ActiveRecord older than every recorded series
        UNKNOWN_PATH = "#{SUPPORT_DIR}/unknown.gemfile"

        # @return [Array<String>] support gemfiles written by kettle-jem-appraisals 0.1.4 and earlier
        LEGACY_PATHS = [
          "gemfiles/modular/activerecord_support.gemfile",
          "gemfiles/modular/activerecord_support_modern.gemfile"
        ].freeze

        class << self
          # @param path [String] a gemfile path, with or without the leading +gemfiles/+
          # @return [Boolean] whether +path+ names an ActiveRecord support gemfile
          def support_gemfile?(path)
            normalized = path.to_s.strip.sub(%r{\Agemfiles/}, "")
            return true if normalized.start_with?("#{SUPPORT_DIR.delete_prefix("gemfiles/")}/")

            LEGACY_PATHS.any? { |legacy| legacy.delete_prefix("gemfiles/") == normalized }
          end
        end

        # @return [String] absolute path to the project root
        attr_reader :base_dir

        # @param base_dir [String] path to the project root
        def initialize(base_dir: Dir.pwd)
          @base_dir = base_dir
        end

        # Writes the support gemfile needed by each ActiveRecord version, skipping
        # hand-maintained files, and removes support gemfiles generated by
        # kettle-jem-appraisals 0.1.4 and earlier.
        #
        # @param activerecord_versions [Array<String>] ActiveRecord versions in the matrix
        # @return [Hash{String => Symbol}] relative path => +:written+, +:kept+, or +:removed+
        def generate(activerecord_versions)
          results = {}
          activerecord_versions.map { |version| group_for(version) }.uniq.each do |group|
            relative_path = path_for(group)
            absolute = File.join(base_dir, relative_path)
            if hand_maintained?(absolute)
              results[relative_path] = :kept
              next
            end

            FileUtils.mkdir_p(File.dirname(absolute))
            File.write(absolute, build_content(group))
            results[relative_path] = :written
          end

          LEGACY_PATHS.each do |relative_path|
            absolute = File.join(base_dir, relative_path)
            next unless File.exist?(absolute) && !hand_maintained?(absolute)

            FileUtils.rm_f(absolute)
            results[relative_path] = :removed
          end
          results
        end

        # @param activerecord_version [String, Gem::Version] the entry's ActiveRecord version
        # @return [String] the matching support gemfile, relative to +gemfiles/+ (for +eval_gemfile+)
        def eval_path_for(activerecord_version)
          path_for(group_for(activerecord_version)).delete_prefix("gemfiles/")
        end

        # @param activerecord_version [String, Gem::Version]
        # @return [Array<String>] the sqlite3 requirements for that ActiveRecord version
        def sqlite3_requirements(activerecord_version)
          group = group_for(activerecord_version)
          group ? group.first.requirements : []
        end

        # Advisories that affect every sqlite3 series the requirements allow.
        #
        # @param activerecord_version [String, Gem::Version]
        # @return [Array<String>] advisory ids; empty when a fixed sqlite3 release is allowed
        def unfixed_sqlite3_advisories(activerecord_version)
          requirement = Gem::Requirement.new(*sqlite3_requirements(activerecord_version))
          allowed = Kettle::Rb::GemFloors.entries_for("sqlite3").select { |entry|
            requirement.satisfied_by?(Gem::Version.new(entry.floor))
          }
          return [] if allowed.empty? || allowed.any? { |entry| entry.unpatched_advisories.empty? }

          allowed.flat_map(&:unpatched_advisories).uniq.sort
        end

        private

        # Runs of consecutive ActiveRecord series with identical sqlite3 requirements.
        def groups
          @groups ||= Kettle::Rb::GemDependencies.entries_for("activerecord", "sqlite3")
            .sort_by { |entry| Gem::Version.new(entry.series) }
            .chunk_while { |older, newer| older.requirements == newer.requirements }
            .to_a
        end

        def group_for(activerecord_version)
          series = Kettle::Rb::GemFloors.series_for(activerecord_version)
          return unless series

          version = Gem::Version.new(series)
          groups.reverse.find { |group| Gem::Version.new(group.first.series) <= version }
        end

        def path_for(group)
          group ? "#{SUPPORT_DIR}/v#{group.first.series}.gemfile" : UNKNOWN_PATH
        end

        def hand_maintained?(absolute)
          File.exist?(absolute) && !File.read(absolute).include?(GENERATED_HEADER)
        end

        def label(group)
          return "ActiveRecord without recorded sqlite3 requirements" unless group

          first = group.first.series
          last = group.last.series
          range =
            if group.equal?(groups.last)
              "#{first}+"
            elsif first == last
              first
            else
              "#{first}–#{last}"
            end
          "ActiveRecord #{range}"
        end

        def build_content(group)
          requirements = group ? group.first.requirements : []
          sqlite3 = [%("sqlite3"), *requirements.map(&:inspect), "platforms: [:ruby]"].join(", ")
          notes = []
          notes << "# sqlite3 requirement from kettle-rb: #{group.last.source}" if group
          unfixed = group ? unfixed_sqlite3_advisories(group.first.series) : []
          notes << "# kettle-rb: no sqlite3 release allowed here fixes #{unfixed.join(", ")}" unless unfixed.empty?

          <<~GEMFILE
            # frozen_string_literal: true

            #{GENERATED_HEADER}
            # Database drivers for #{label(group)}: sqlite3 on MRI/TruffleRuby,
            # activerecord-jdbcsqlite3-adapter on JRuby (its release series tracks ActiveRecord).
            #{notes.join("\n")}
            gem #{sqlite3}

            platforms :jruby do
              gem "activerecord-jdbcsqlite3-adapter", ">= 1.3"
              gem "bigdecimal", ">= 1"
            end
          GEMFILE
        end
      end
    end
  end
end
