# frozen_string_literal: true

require "kettle/rb"

module Kettle
  module Jem
    module Appraisals
      # Generates modular gemfile files for the appraisal matrix.
      #
      # Creates per-version gemfiles organized by gem name and Ruby series:
      #   +gemfiles/modular/{gem_name}/{ruby_series}/v{version}.gemfile+
      #
      # Gems tracked by +Kettle::Rb::GemFloors+ get their minor series' security
      # floor (e.g. +"~> 7.1.0", ">= 7.1.6"+). Exact patch versions stay pinned.
      # A comment notes advisories that no release in the series fixes, and an
      # exact patch version below the floor.
      #
      # @example
      #   gen = ModularGemfileGenerator.new(base_dir: "/path/to/project")
      #   gen.generate(gem_name: "activerecord", version: "7.1", ruby_series: "r3")
      #   #=> "gemfiles/modular/activerecord/r3/v7.1.gemfile"
      class ModularGemfileGenerator
        # @return [String] absolute path to the project root (where +gemfiles/+ lives)
        attr_reader :base_dir

        # @param base_dir [String] path to the project root (defaults to the current working directory)
        def initialize(base_dir: Dir.pwd)
          @base_dir = base_dir
        end

        # Generates a modular gemfile for a tier1 gem, including its sub-dependencies.
        #
        # Writes the file to disk and returns the relative path.
        #
        # @param gem_name [String] tier1 gem name (e.g., +"activerecord"+)
        # @param version [String] minor version string (e.g., +"7.1"+)
        # @param ruby_series [String] Ruby series bucket (e.g., +"r3"+)
        # @param sub_deps [Hash{String => String}] sub-dependency name → version constraint
        #   (e.g., +{"sqlite3" => "1.6.9"}+)
        # @return [String] the relative path to the generated gemfile
        def generate(gem_name:, version:, ruby_series:, sub_deps: {})
          dir = File.join(base_dir, "gemfiles", "modular", gem_name, ruby_series)
          FileUtils.mkdir_p(dir)

          filename = "v#{version}.gemfile"
          path = File.join(dir, filename)
          content = build_content(gem_name, version, sub_deps)

          File.write(path, content)
          File.join("gemfiles", "modular", gem_name, ruby_series, filename)
        end

        # Generates a modular gemfile for a tier2 gem (no sub-dependencies).
        #
        # Writes the file to disk and returns the relative path.
        #
        # @param gem_name [String] tier2 gem name (e.g., +"omniauth"+)
        # @param version [String] minor version string (e.g., +"2.1"+)
        # @param ruby_series [String] Ruby series bucket (e.g., +"r3"+)
        # @return [String] the relative path to the generated gemfile
        def generate_tier2(gem_name:, version:, ruby_series:)
          dir = File.join(base_dir, "gemfiles", "modular", gem_name, ruby_series)
          FileUtils.mkdir_p(dir)

          filename = "v#{version}.gemfile"
          path = File.join(dir, filename)
          content = build_tier2_content(gem_name, version)

          File.write(path, content)
          File.join("gemfiles", "modular", gem_name, ruby_series, filename)
        end

        private

        def build_content(gem_name, version, sub_deps)
          lines = header_lines
          lines.concat(gem_lines(gem_name, version, pinned_requirements(gem_name, version)))

          sub_deps.each do |dep_name, dep_version|
            lines.concat(gem_lines(dep_name, dep_version, floored_requirements(dep_name, dep_version, ["~> #{dep_version}"])))
          end

          lines << ""
          "#{lines.join("\n")}\n"
        end

        def build_tier2_content(gem_name, version)
          lines = header_lines
          lines.concat(gem_lines(gem_name, version, pinned_requirements(gem_name, version)))
          lines << ""
          "#{lines.join("\n")}\n"
        end

        def header_lines
          [
            "# frozen_string_literal: true",
            "",
            "# Generated by kettle-jem-appraisals"
          ]
        end

        def gem_lines(gem_name, version, requirements)
          advisory_notes(gem_name, version, requirements) + ["gem #{[gem_name, *requirements].map(&:inspect).join(", ")}"]
        end

        # Minor versions get the series' security floor; exact patch versions stay pinned.
        def pinned_requirements(gem_name, version)
          requirement = version_requirement(version)
          return [requirement] if exact_patch?(version)

          floored_requirements(gem_name, version, [requirement])
        end

        def floored_requirements(gem_name, version, requirements)
          floor = floor_above(gem_name, version)
          floor ? requirements + [">= #{floor}"] : requirements
        end

        def advisory_notes(gem_name, version, requirements)
          notes = []
          unpatched = Kettle::Rb::GemFloors.unpatched_advisories(gem_name, version)
          unless unpatched.empty?
            series = Kettle::Rb::GemFloors.series_for(version)
            notes << "# kettle-rb: no #{gem_name} #{series} release fixes #{unpatched.join(", ")}"
          end

          floor = floor_above(gem_name, version)
          if floor && !requirements.include?(">= #{floor}")
            notes << "# kettle-rb: #{gem_name} #{version} is below the #{gem_name} security floor #{floor}"
          end
          notes
        end

        # @return [String, nil] the security floor when it is newer than +version+
        def floor_above(gem_name, version)
          floor = Kettle::Rb::GemFloors.floor(gem_name, version)
          floor if floor && Gem::Version.new(floor) > Gem::Version.new(version)
        end

        def exact_patch?(version)
          version.to_s.split(".").length >= 3
        end

        def version_requirement(version)
          if exact_patch?(version)
            "~> #{version}"
          else
            "~> #{version}.0"
          end
        end
      end
    end
  end
end
